### ISSUE TITLE
PDO + Spatialite - Any way at all?

### ISSUE THREAD

**Issue by zlanich** [brick/geo#12]
Do you know if it's possible (in any way at all) to get PDO + Spatialite working?

My issue is that Laravel relies on PDO and there's no way (that I know of) to actually call ->loadExtension('mod_spatialite.so'); using pdo_sqlite, so you have to use SELECT load_extension('mod_spatialite');, which is obviously disabled.

I'm even open to somehow recompiling php 7.2 without that SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION flag, but I'm not sure where to start because I honestly have no idea "how" SQLite is compiled into php (since it's included out of the box in Debian).

Thanks!

**Comment by BenMorel** [comment]
Hi, as explained in the README, this is a PDO limitation:
https://bugs.php.net/bug.php?id=64810

Someone there provides a link to a StackOverflow question with a patch for PHP 5.3 (which would need to be adapted to PHP 7).

Before recompiling PHP though, I would strongly suggest that you create an additional SQLite3 connection to an in-memory database, and use this one as your geometry engine:

```
$sqlite3 = new SQLite3(':memory:');
$sqlite3->loadExtension('mod_spatialite.so');
GeometryEngineRegistry::set(new SQLite3Engine($sqlite3));
```

It does not matter if it's not the same as the connection to your main database!

**Comment by zlanich** [comment]
@BenMorel Thanks for your help! Could you clarify a bit on the "It does not matter if it's not the same as the connection to your main database!" part? Are you suggesting I creating another raw `\SQLite3` instance and calling `loadExtension()`, etc on it will affect the SQLite instance used in the PDO connection and all me to use geometry functions in SQL?

**Comment by BenMorel** [comment]
No, it will not allow you to call geometry functions in your SQL queries executed on your PDO connection.
However, it will allow you to call geometry functions in PHP (they will internally be executed by SpatiaLite on your SQLite3 instance).

For example, you won't be able to return the area of a polygon in SQL:

```sql
SELECT ST_Area(boundary) FROM zones WHERE id = 1; // executed via PDO, will not work
```

...but you will be able to instantiate the polygon in PHP, and then calculate its area:

```php
$wkt = $pdo->query('SELECT ST_ASText(boundaryWKT) FROM zones WHERE id = 1')->fetchColumn();
$polygon = Polygon::fromText($wkt);
echo $polygon->area(); // executed via SQLite3, will work
```

Providing you with a way to bypass the PDO `load_extension` limitation to get GIS functions in your SQL queries is not the aim of this library, hope this makes sense!

**Comment by zlanich** [comment]
Yea, I had a feeling that wasn't possible. Unfortunately, I need to be able to query by distance, etc. Not sure how to get there yet. It really stinks too because I "need" Spatialite for the unit tests for my entire application, and can't seem to find a way yet.

Let me know if you have any ideas!

**Comment by BenMorel** [comment]
The way I would do it is to try to remove your dependency on PDO (replace it with SQLite3), or at least allow your app to query SQLite3 in parallel. Nothing prevents you from using PDO in one place and SQLite3 in another.

Oh, and for what it's worth, you should add your +1 to the PHP [bug report](https://bugs.php.net/bug.php?id=64810)!

**Comment by zlanich** [comment]
@BenMorel If it were that easy for me to switch to just SQLite3, I just would, but unfortunately Laravel's Eloquent Builder, etc is tied heavily enough to PDO that it would be a ton of work to try to override everything, and a bit over my head atm. I may have to at some point if it never gets resolved, though.

Just voted and commented on the bug report. Thanks for pointing me to that so I can follow it now 😃
