### ISSUE TITLE
IO GeoJSON Support

### ISSUE THREAD

**Issue by michaelcurry** [brick/geo#13]
@BenMorel : It looks like Geojson, KML, etc... is not currently supported.  If a Pull Request came in that expanded the ability to Init and ToString multiple Geo String Types, would you be up for reviewing / merging?

**Comment by BenMorel** [comment]
Hi Michael, sure, I welcome pull requests!

This would fit very well as standalone reader/writer classes in the `IO` sub-namespace, unless you had something else in mind when you say Init / ToString?

**Comment by michaelcurry** [comment]
I have not dug in too much yet, but I am hoping to get some time this weekend.

P.S: Great Lib and thanks for writing it!

**Comment by michaelcurry** [comment]
@BenMorel :  I 100% see what you mean by the `IO` sub-namespace :+1: 

*Question:*
The GeoJSON Spec (https://tools.ietf.org/html/rfc7946#section-3) specifies `A GeoJSON object represents a Geometry, Feature, or collection of Features.`.  Because This Geo Lib does not account for "parameters" OR multiple Gemonstries from a single "read" Would you be ok with the parser only accepting GeoJSON `Geometry`?

NOTE: I could see an argument for accepting GeoJSON `Geometry` OR `Feature` as they only have one `Geometry` within them, but a `Collection` may hold multiple `Geometry` and the current Readers do not support Multiple `Brick\Geo\Geometry` returns.  Example: https://github.com/brick/geo/blob/master/src/IO/WKTReader.php#L23

**Comment by michaelcurry** [comment]
@BenMorel  Apologies for the long question...  I think I just answered my own question.  

It looks like the other Parsers throw a `GeometryIOException` if there is a "type" that is not supported (https://github.com/brick/geo/blob/master/src/Exception/GeometryIOException.php#L55)

Unless you specify otherwise, I will stick to this standard, and new "types" can be added to the parser as development continues. :+1:

**Comment by michaelcurry** [comment]
@BenMorel: I have attached a `Work In Progress` Pull Request #14 for you to give feedback on before I take the time to complete the "Read" functionality for GeoJSON.  

Any feedback would be great.  Comments on the Pull Request itself might be the best way to remedy any issues.

**Comment by BenMorel** [comment]
Hi Michael,

> A GeoJSON object represents a Geometry, Feature, or collection of Features.. Because This Geo Lib does not account for "parameters" OR multiple Gemonstries from a single "read" Would you be ok with the parser only accepting GeoJSON Geometry?

I've never used GeoJSON myself, but after a quick look, it looks to me that a GeoJSON object contains either a `Feature`, or a `FeatureCollection` (I've not found any mention of a `"type": "Geometry"` in the root GeoJSON object?); and that each `Feature` contains exactly one Geometry, plus arbitrary data (that we won't import here).

If this is correct, I would convert to GeoJSON object to:
- if it contains a Feature, to whatever Geometry the Feature contains
- if it contains a FeatureCollection, to a GeometryCollection that would be populated with each Geometry contained in each Feature the FeatureCollection contains

> It looks like the other Parsers throw a GeometryIOException if there is a "type" that is not supported (https://github.com/brick/geo/blob/master/src/Exception/GeometryIOException.php#L55)

IIRC, this is when reading a WKT that would contain an unsupported type; this should not be necessary here, as all Geometry types in the GeoJSON spec are supported by this library!

**Comment by michaelcurry** [comment]
@BenMorel In reply to `FeatureCollection`:

The first version of the GeoJSON read, I don't plan to implement `FeatureCollection` type support, but After all of the types are complete, there may be an easy way to tack this on.  👍

**Comment by BenMorel** [comment]
I don't think this should be hard to add straight away, maybe it's worth thinking about it from the beginning?

Something like:

```php
public function readGeometry(array $geoJsonObject) : Geometry
{
    switch (strtolower($geoJsonObject['type'])) {
        case 'feature':
            return $this->readGeometryFromFeature($geoJsonObject);

        case 'featurecollection':
            $geometries = [];
            foreach ($geoJsonObject['features'] as $feature) {
                $geometries[] = $this->readGeometryFromFeature($feature);
            }
            return GeometryCollection::of(...$geometries);
}

private function readGeometryFromFeature(array $feature) : Geometry
{
    $geometry = $feature['geometry'];

    switch ($geometry['type']) {
        // ...
    }
}
```

**Comment by michaelcurry** [comment]
Good idea @BenMorel! I apparently overlooked the ability to return a `GeometryCollection`...  Apologies;  I have not used this Lib to date, but am excited to start using it in production once the GeoJSON support is complete.

Note: I have to run for a while but hope to continue working on the Pull Request later tonight/this weekend.

**Comment by michaelcurry** [comment]
@BenMorel:  GeoJSON "read" functionality is complete.  I am about to start on "write" functionality 👍

**Comment by michaelcurry** [comment]
@BenMorel: Pull Request is ready for you to look at 👍 

I have to step out for a bit, but I will check any replies later tonight and make adjustments.
PR Link: #14

**Comment by michaelcurry** [comment]
**First Pull Request Review Complete:** (For Tracking)
526ed7fdf5c7aeb88a9eadd9f516700feb0c10d6 Remove GeoJSON spatial reference systems (SRIDs)
a3eda381fe0c7cb6e8fb619f3390f74641d02a9a Add string $context to GeometryIOException::invalidGeoJSON(...)
9cfd97f247065eb0c32c692ed728c3ee105f2281 Refactor GeoJSON Writer
651a5a419d692defd75d2e9189dd7ffce5d6af2d Merge GeoJSON Abstract Reader into Reader class
52cf6bfe7071325c2fb5cef3cf643f55c3d56ee0 Add GeoJSON json_decode checks in GeoJSONReader::read()
f58518c10d4a8ae0735da59d385981f92f49c6c0 Return TypeHint GeoJSONWriter Private Functions
7ee7faa6376fb845da708557bb32618a4d720ee3 Change snake_case Param $geojson_array to camelCase $geojsonArray to follow codebase standards
0aeb6a40d5aa056d5a1531ff7491f41d912c642d Add GeoJSON genPoint ...$coods type as Float
48bd2fbf9b44caee6b8ae8a25d74035b23fd4eda Refactor Checking of GeoJSON FeatureCollection.Fetures array

**Comment by michaelcurry** [comment]
Pull Request update:  All review items have been resolved.  We should be going into final Tweaks :+1:

**Comment by BenMorel** [comment]
Released as [0.2.2](https://github.com/brick/geo/releases/tag/0.2.2). Thank you!

**Comment by BenMorel** [comment]
Note: I added docs about import/export formats to the README, including [GeoJSON](https://github.com/brick/geo#geojson)!

**Comment by michaelcurry** [comment]
This is great @BenMorel 
Thanks for getting this in.  I am excited to extend the functionality in the near future.

**Comment by BenMorel** [comment]
I actually went ahead and added the case-insensitive read and pretty-print write functionality!
https://github.com/brick/geo/releases/tag/0.2.3

Please go ahead if you want to add KML support now 👍

**Comment by michaelcurry** [comment]
@BenMorel  you beat me to it! Thanks for taking the time to do this.

I am actually looking into `GeometryCollection` GeoJson Geometry Objects.  There is a change I will need to use this in a production use case, but I am not sure yet...  Either way,  It looks like I overlooked this Geometry Type when implementing the initial GeoJSONReader...  Please stay tuned for that sometime this coming week... I hope...

**Comment by BenMorel** [comment]
Good point, I see that in the RFC. I created issue #15 to track this.
