### ISSUE TITLE
Class 'GEOSWKBReader' not found

### ISSUE THREAD

**Issue by chs9433** [brick/geo#32]
I keep getting the following error when trying to use the GEOS engine. Looks like this class wasn't included in the package. Any idea where I can find it or resolve the error?

*******************

 Class 'GEOSWKBReader' not found

  at vendor/brick/geo/src/Engine/GEOSEngine.php:63
     59▕      * Class constructor.
     60▕      */
     61▕     public function __construct()
     62▕     {
  ➜  63▕         $this->wkbReader = new \GEOSWKBReader();
     64▕         $this->wkbWriter = new \GEOSWKBWriter();
     65▕ 
     66▕         $this->wktReader = new \GEOSWKTReader();
     67▕         $this->wktWriter = new \GEOSWKTWriter();

  1   database/seeders/TestTableSeeder.php:31
      Brick\Geo\Engine\GEOSEngine::__construct()

      +22 vendor frames 
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by BenMorel** [comment]
Hi, to use the `GEOSEngine`, you need the [geos](https://git.osgeo.org/gitea/geos/php-geos) extension installed!
