### ISSUE TITLE
st_buffer(POLYGON) has not been implemented - SRID 4326 bug

### ISSUE THREAD

**Issue by kasperkamperman** [brick/geo#42]
I got this error when I use the mysql engine (got a similar with postgres).
```
Uncaught PDOException: SQLSTATE[22S00]: <<Unknown error>>: 3618 st_buffer(POLYGON) has not been implemented for geographic spatial reference systems.
```
I'm loading a geojson polygon and wanted to buffer that one. 

The strange thing is that this default example code from the readme worked:
```
$polygon = Polygon::fromText('POLYGON ((0 0, 0 3, 3 3, 0 0))');

echo $polygon->asText()."\n";
$polygon = $polygon->buffer(1);
echo $polygon->asText()."\n";

/* output
POLYGON ((0 0, 0 3, 3 3, 0 0))
POLYGON ((-1 0, -0.98078528040323 -0.19509032201613, -0.92387953251129 -0.38268343236509, -0.83146961230255 -0.5555702330196, -0.70710678118655 -0.70710678118655, -0.5555702330196 -0.83146961230255, -0.38268343236509 -0.92387953251129, -0.19509032201613 -0.98078528040323, 6.1232339957368E-17 -1, 0.19509032201613 -0.98078528040323, 0.38268343236509 -0.92387953251129, 0.5555702330196 -0.83146961230255, 0.70710678118655 -0.70710678118655, 3.7071067811865 2.2928932188135, 3.8314696123025 2.4444297669804, 3.9238795325113 2.6173165676349, 3.9807852804032 2.8049096779839, 4 3, 3.9807852804032 3.1950903220161, 3.9238795325113 3.3826834323651, 3.8314696123025 3.5555702330196, 3.7071067811865 3.7071067811865, 3.5555702330196 3.8314696123025, 3.3826834323651 3.9238795325113, 3.1950903220161 3.9807852804032, 3 4, 0 4, -0.19509032201613 3.9807852804032, -0.38268343236509 3.9238795325113, -0.5555702330196 3.8314696123025, -0.70710678118655 3.7071067811865, -0.83146961230254 3.5555702330196, -0.92387953251129 3.3826834323651, -0.98078528040323 3.1950903220161, -1 3, -1 0))
*/
```
There is no error throw, and the buffer function works. 

I figured that the SRID by default is 0. 
However I set this to 4326 like: 

```
$polygon = Polygon::fromText('POLYGON ((0 0, 0 3, 3 3, 0 0))', 4326);
```
I get the _st_buffer not implemented_ error when I run the above code...

I figured a hacky workaround to remove the 4326 SRID
```
$polygon = Polygon::fromText('POLYGON ((0 0, 0 3, 3 3, 0 0))', 4326);

// set SRID to 0... 
$polygon = Polygon::fromText($polygon->asText(), 0);

echo $polygon->asText()."\n";
$polygon = $polygon->buffer(1);//->asText();
echo $polygon->asText()."\n";
```
Like this I could process my geojson polygons as well (I used this example code to make a minimal example of the bug).

**Comment by BenMorel** [comment]
Hi, the issue is not with this library, but with the GIS implementation of MySQL / PostgreSQL. I guess the reason why this operation is not supported on SRID 4326 is that it must be hard to calculate on the spheroid.

Whereas on SRID 0, it is assumed that the coordinate system is flat, so calculations must be easier to perform.

Don't forget that this library is just a wrapper around a geometry engine (here, a database), so you're inherently limited by the capabilities of this engine.

Switching SRIDs is probably your best bet here, and probably good enough if your polygon & buffer are not too large, and not too close to the poles!

**Comment by kasperkamperman** [comment]
Thanks for your reaction. I understood this library is a wrapper, however the readme doesn't make it very clear that different coordinate systems are not taken into account. 

I assume because you offered the GeoJson output, you also supported the default coordinate system of GeoJson (SRID 4326). 

Based on your reaction I did some reading (I'd call myself a geo expert and was just slightly aware of the coordinate system issues and work arounds). I just write down my search, in case someone else runs into this. 

This resource was helpful to understand the issues. 
https://postgis.net/workshops/postgis-intro/geography.html

Since SRID 4326 is widely used I think it make sense to make users of your library aware of the support. 

PostGis distinguisses geometry and geography. The latter supports the spherical coordinate system. 

From your reaction I understand you don't support different coordinate systems? 

Because in PostGIS it's possible:
https://postgis.net/workshops/postgis-intro/geography.html#using-geography

And in MySQL too if I read it correctly:
https://dev.mysql.com/doc/refman/8.0/en/spatial-reference-systems.html

**Comment by kasperkamperman** [comment]
Ok, I see in the details that some functions only support cartesian:

_The SRID of the geometry argument must be 0 because [ST_Buffer()](https://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html#function_st-buffer) supports only the Cartesian coordinate system. If any geometry argument is not a syntactically well-formed geometry, an [ER_GIS_INVALID_DATA](https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html#error_er_gis_invalid_data) error occurs._
https://dev.mysql.com/doc/refman/5.7/en/spatial-operator-functions.html#function_st-buffer

**Comment by BenMorel** [comment]
> From your reaction I understand you don't support different coordinate systems?

The objects provided by the library *do* store the SRID, but do not do anything with it, other than passing it to the geometry engine. What the geometry engine does with it is outside the scope of the project.

> PostGis distinguisses geometry and geography. The latter supports the spherical coordinate system.

It's a long standing issue that brick/geo only maps to `GEOMETRY` objects and not PostGIS' proprietary `GEOGRAPHY` objects. I don't have enough understanding of the differences between the two of them to provide a custom implementation for PostGIS, but if you do, please feel free to propose a pull request!

(In particular, I fail to understand why PostGIS chose to implement a different `GEOGRAPHY` type, when they could have made the calculations available on `GEOMETRY` with SRID 4326? Please enlighten me if you know the answer.)
