### ISSUE TITLE
Can you add support for MakeValid() in the GeometryEngine?

### ISSUE THREAD

**Issue by timhj** [brick/geo#45]
It's great to have the option of isValid, in instances where there is a problem it would be good to natively be able to run the geometry through the MakeValid method and see if it's fixable.

Thoughts?

**Comment by timhj** [comment]
No longer required for me but might still be worth thinking about. Closing the ticket.

**Comment by BenMorel** [comment]
Reopening, I will try to add support for this one!

**Comment by BenMorel** [comment]
Implemented in [0.10.0](https://github.com/brick/geo/releases/tag/0.10.0)!
