### ISSUE TITLE
Add support for ST_Split

### ISSUE THREAD

**Issue by qleraps** [brick/geo#47]
How hard would it be to allow the ST_Split operation on geometries? It would be really useful for us in our current projekt :)
Kind regards
Morten, qLER ApS

**Comment by BenMorel** [comment]
Hi, `GeometryEngine::split()` has been added in [version 0.11.0](https://github.com/brick/geo/releases/tag/0.11.0) :slightly_smiling_face:

**Comment by qleraps** [comment]
Amazing, thank you! :) some beer/coffee money has already be sent your way :)
Cheers, Morten

**Comment by BenMorel** [comment]
Thanks a lot @qleraps, much appreciated :slightly_smiling_face:
