### ISSUE TITLE
Public query functions for DatabaseEngine

### ISSUE THREAD

**Issue by cevou** [brick/geo#5]
It would be nice if you could use the query functions from the DatabaseEngine to do operations on geometry objects withing the application. Currently they are deplcared as private. Is there any reason (besides that there is no common API with the GEOS lib) why this is done?

**Comment by BenMorel** [comment]
These methods are used internally to implement the `GeometryEngine` interface, why would you use them directly? Do you have a scenario in mind?

**Comment by cevou** [comment]
For example I have a Polygon object which I would like to simplyfy using the ST_Simplyfy function. This could be done by calling `$engine->queryGeometry('ST_Simplyfy', [$geom, $tolerance])`

**Comment by BenMorel** [comment]
Hmm I see. The idea is that `GeometryEngine` should be an implementation detail though, and is not supposed to be interacted with directly after you have set it up.

My view would be that if we want this kind of support, the function `simplify()` should be added to the `Geometry` class (and therefore to the `GeometryEngine` interface), however we have to check if it's supported by other platforms as it's not part of the OpenGIS specification AFAIK (all current functions are taken from this spec).

**Comment by cevou** [comment]
Yes, `simplyfy()` is not part of the OpenGIS specification and this project is clearly marked as an implementation of this spec. So we shouldn't add any non standard functions. But it would be nice to have such an API, maybe in a seperate lib which can be used by this project.

**Comment by BenMorel** [comment]
TBH, implementing the OpenGIS spec is a *minimum* requirement, but I can see no reason not to add additional methods on top of the spec, especially if these methods are well supported across database vendors and GEOS.

The one you mention is supported by PostGIS, GEOS, and SpatiaLite, not by MySQL unfortunately.

But there are already a few methods that are not implemented by some engines, see [this](https://github.com/brick/geo/blob/master/src/Engine/GEOSEngine.php#L225) for example.

So I'm potentially OK to add methods that are not supported by all engines / not defined by the spec, provided that:

- they are mainstream enough to be supported by more than one engine
- we expose this clearly in the documentation.

We could have a table that lists all the functions, whether or not they're defined by OpenGIS, and their support for every platform:

Function name | OpenGIS standard | GEOS | PostGIS | MySQL
--- | --- | --- | --- | ---
`union()`  | ✓ | ✓ | ✓ | ✓
`simplify()`  | ✕ | ✓ | ✓ | ✕

What do you think?

**Comment by cevou** [comment]
I think, that this is a good idea. Basically we could create the table with all functions provided by any of the implementations and add a checkmark if the function is already implemented in this lib.

**Comment by cevou** [comment]
Implemented in #9
